import { Injectable } from '@angular/core';
import { UnidadMedidaModel } from '../models/unidadmedida';

@Injectable({
  providedIn: 'root'
})
export class UnidadMedidaService {
  private unidadMedidaList: UnidadMedidaModel[] = [
    { tume_nid:  1, tume: "BOBI", tume_cdesc: "BOBINAS"            , tume_csimbolo:"4A"  },
    { tume_nid:  2, tume: "BALD", tume_cdesc: "BALDE"              , tume_csimbolo:"BJ"  },
    { tume_nid:  3, tume: "BAR",  tume_cdesc: "BARRILES"           , tume_csimbolo:"BLL" },
    { tume_nid:  4, tume: "BOLSA",tume_cdesc: "BOLSA"              , tume_csimbolo:"BG"  },
    { tume_nid:  5, tume: "BOTE", tume_cdesc: "BOTELLAS"           , tume_csimbolo:"BO"  },
    { tume_nid:  6, tume: "CJA",  tume_cdesc: "CAJA"               , tume_csimbolo:"BX"  },
    { tume_nid:  7, tume: "CART", tume_cdesc: "CARTONES"           , tume_csimbolo:"CT"  },
    { tume_nid:  8, tume: "CM²",  tume_cdesc: "CENTIMETRO CUADRADO", tume_csimbolo:"CMK" },
    { tume_nid:  9, tume: "CM³",  tume_cdesc: "CENTIMETRO CUBICO"  , tume_csimbolo:"CMQ" },
    { tume_nid: 10, tume: "CM"   , tume_cdesc: "CENTIMETRO LINEAL", tume_csimbolo:"CMT"},
    { tume_nid: 11, tume: "CIEN" , tume_cdesc: "CIENTO DE UNIDADES", tume_csimbolo:"CEN"},
    { tume_nid: 12, tume: "CIL"  , tume_cdesc: "CILINDRO", tume_csimbolo:"CY"},
    { tume_nid: 13, tume: "CON"  , tume_cdesc: "CONOS", tume_csimbolo:"CJ"},
    { tume_nid: 14, tume: "DOC"  , tume_cdesc: "DOCENA", tume_csimbolo:"DZN"},
    { tume_nid: 15, tume: "DOC6" , tume_cdesc: "DOCENA POR 10**6", tume_csimbolo:"DZP"},
    { tume_nid: 16, tume: "FARD" , tume_cdesc: "FARDO", tume_csimbolo:"BE"},
    { tume_nid: 17, tume: "GLN"  , tume_cdesc: "GALON INGLES (4,545956L)", tume_csimbolo:"GLI"},
    { tume_nid: 18, tume: "GRM"  , tume_cdesc: "GRAMO", tume_csimbolo:"GRM"},
    { tume_nid: 19, tume: "GRUE" , tume_cdesc: "GRUESA", tume_csimbolo:"GRO"},
    { tume_nid: 20, tume: "HECT" , tume_cdesc: "HECTOLITRO", tume_csimbolo:"HLT"},
    { tume_nid: 21, tume: "HOJA" , tume_cdesc: "HOJA", tume_csimbolo:"LEF"},
    { tume_nid: 22, tume: "SET"  , tume_cdesc: "JUEGO", tume_csimbolo:"SET"},
    { tume_nid: 23, tume: "KGM"  , tume_cdesc: "KILOGRAMO", tume_csimbolo:"KGM"},
    { tume_nid: 24, tume: "KLM"  , tume_cdesc: "KILOMETRO", tume_csimbolo:"KTM"},
    { tume_nid: 25, tume: "KWH"  , tume_cdesc: "KILOVATIO HORA", tume_csimbolo:"KWH"},
    { tume_nid: 26, tume: "KT"   , tume_cdesc: "KIT", tume_csimbolo:"KT"},
    { tume_nid: 27, tume: "LATA" , tume_cdesc: "LATAS", tume_csimbolo:"CA"},
    { tume_nid: 28, tume: "LBR"  , tume_cdesc: "LIBRAS", tume_csimbolo:"LBR"},
    { tume_nid: 29, tume: "LTR"  , tume_cdesc: "LITRO", tume_csimbolo:"LTR"},
    { tume_nid: 30, tume: "MWH"  , tume_cdesc: "MEGAWATT HORA", tume_csimbolo:"MWH"},
    { tume_nid: 31, tume: "METR" , tume_cdesc: "METRO", tume_csimbolo:"MTR"},
    { tume_nid: 32, tume: "M²"   , tume_cdesc: "METRO CUADRADO", tume_csimbolo:"MTK"},
    { tume_nid: 33, tume: "M³"   , tume_cdesc: "METRO CUBICO", tume_csimbolo:"MTQ"},
    { tume_nid: 34, tume: "MM"   , tume_cdesc: "MILIGRAMOS", tume_csimbolo:"MGM"},
    { tume_nid: 35, tume: "MLT"  , tume_cdesc: "MILILITRO", tume_csimbolo:"MLT"},
    { tume_nid: 36, tume: "MMT"  , tume_cdesc: "MILIMETRO", tume_csimbolo:"MMT"},
    { tume_nid: 37, tume: "MM²"  , tume_cdesc: "MILIMETRO CUADRADO", tume_csimbolo:"MMK"},
    { tume_nid: 38, tume: "MM³"  , tume_cdesc: "MILIMETRO CUBICO", tume_csimbolo:"MMQ"},
    { tume_nid: 39, tume: "MLL"  , tume_cdesc: "MILLARES", tume_csimbolo:"MLL"},
    { tume_nid: 40, tume: "UM"   , tume_cdesc: "MILLON DE UNIDADES", tume_csimbolo:"UM"},
    { tume_nid: 41, tume: "ONZ"  , tume_cdesc: "ONZAS", tume_csimbolo:"ONZ"},
    { tume_nid: 42, tume: "PALET", tume_cdesc: "PALETAS", tume_csimbolo:"PF"},
    { tume_nid: 43, tume: "PAQT" , tume_cdesc: "PAQUETE", tume_csimbolo:"PK"},
    { tume_nid: 44, tume: "PAR"  , tume_cdesc: "PAR", tume_csimbolo:"PR"},
    { tume_nid: 45, tume: "PIES" , tume_cdesc: "PIES", tume_csimbolo:"FOT"},
    { tume_nid: 46, tume: "PIE²" , tume_cdesc: "PIES CUADRADOS", tume_csimbolo:"FTK"},
    { tume_nid: 47, tume: "PIE³" , tume_cdesc: "PIES CUBICOS", tume_csimbolo:"FTQ"},
    { tume_nid: 48, tume: "PZA"  , tume_cdesc: "PIEZAS", tume_csimbolo:"C62"},
    { tume_nid: 49, tume: "PLAC" , tume_cdesc: "PLACAS", tume_csimbolo:"PG"},
    { tume_nid: 50, tume: "PLIEG", tume_cdesc: "PLIEGO", tume_csimbolo:"ST"},
    { tume_nid: 51, tume: "PULG" , tume_cdesc: "PULGADAS", tume_csimbolo:"INH"},
    { tume_nid: 52, tume: "RESM" , tume_cdesc: "RESMA", tume_csimbolo:"RM"},
    { tume_nid: 53, tume: "TAMB" , tume_cdesc: "TAMBOR", tume_csimbolo:"DR"},
    { tume_nid: 54, tume: "TMC"  , tume_cdesc: "TONELADA CORTA", tume_csimbolo:"STN"},
    { tume_nid: 55, tume: "TML"  , tume_cdesc: "TONELADA LARGA", tume_csimbolo:"LTN"},
    { tume_nid: 56, tume: "TM"   , tume_cdesc: "TONELADAS", tume_csimbolo:"TNE"},
    { tume_nid: 57, tume: "TUBO" , tume_cdesc: "TUBOS", tume_csimbolo:"TU"},
    { tume_nid: 58, tume: "UNI"  , tume_cdesc: "UNIDAD", tume_csimbolo:"NIU"},
    { tume_nid: 59, tume: "UNIS" , tume_cdesc: "UNIDAD (SERVICIOS)", tume_csimbolo:"ZZ"},
    { tume_nid: 60, tume: "GLNS" , tume_cdesc: "US GALON (3,7843 L)", tume_csimbolo:"GLL"},
    { tume_nid: 61, tume: "YARD" , tume_cdesc: "YARDA", tume_csimbolo:"YRD"},
    { tume_nid: 62, tume: "YARD²", tume_cdesc: "YARDA CUADRADA", tume_csimbolo:"YDK"},
    { tume_nid: 63, tume: "H-H"  , tume_cdesc: "HORAS HOMBRE", tume_csimbolo:"ZZ"},
    { tume_nid: 64, tume: "H-M"  , tume_cdesc: "HORAS MAQUINA", tume_csimbolo:"ZZ"},
    { tume_nid: 65, tume: "%MO"  , tume_cdesc: "PORCENTAJE DE DESGASTE", tume_csimbolo:"ZZ"},
  ];
  constructor() { }
  getUnidadMedidas(){
    return this.unidadMedidaList;
  }
}
